### ISSUE TITLE
installation error in windows system

### ISSUE THREAD

**Issue by NchuYJ** [saezlab/lipyd#7]
`(base) PS E:\lcms_WF\lipyd> pip install git+https://github.com/saezlab/lipyd.git                                              
Collecting git+https://github.com/saezlab/lipyd.git
  Cloning https://github.com/saezlab/lipyd.git to c:\users\498017191\appdata\local\temp\pip-req-build-u_yebgkv
  Running command git clone --filter=blob:none --quiet https://github.com/saezlab/lipyd.git 'C:\Users\498017191\AppData\Local\Temp\pip-req-build-u_yebgkv'
  Resolved https://github.com/saezlab/lipyd.git to commit 85d6fae473dbde7a0244202302abc716a4c6a25d
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      <string>:21: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
      Traceback (most recent call last):
        File "F:\Anaconda\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 351, in <module>
          main()
        File "F:\Anaconda\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "F:\Anaconda\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\498017191\AppData\Local\Temp\pip-build-env-kwciy17j\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\498017191\AppData\Local\Temp\pip-build-env-kwciy17j\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "C:\Users\498017191\AppData\Local\Temp\pip-build-env-kwciy17j\overlay\Lib\site-packages\setuptools\build_meta.py", line 484, in run_setup
          super(_BuildMetaLegacyBackend,
        File "C:\Users\498017191\AppData\Local\Temp\pip-build-env-kwciy17j\overlay\Lib\site-packages\setuptools\build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 30, in <module>
      UnicodeDecodeError: 'gbk' codec can't decode byte 0x93 in position 10: illegal multibyte sequence
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.`

pycurl package can be installed, but hard to find a proper version. After, the code 'pip install git+https://github.com/saezlab/lipyd.git      ' was used, there comes out one error mentioning the building wheel failed.

**Comment by deeenes** [comment]
Hello, Looks like on your system GBK encoding is the default, or it is set as a default for Python. You can try to run the command with a different encoding. These can be set by environment variables. I think most likely the `LC_CTYPE` env var matters here, but [maybe](https://stackoverflow.com/a/27066059/854988) it's the [`PYTHONIOENCODING`](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONIOENCODING). So run the command like this:

```
LC_CTYPE="en_GB.UTF-8" pip install git+https://github.com/saezlab/lipyd.git
```

Because you're using Windows, [the labels of the locales will be different](https://stackoverflow.com/a/956084/854988), this you have to find out for yourself.

Another way could be to change your operating system's default encoding to UTF-8.

Also, here you get the error by pip, to see where it exactly comes from, you could just clone this repo and import all submodules one by one:

```
git clone --depth 1 https://github.com/saezlab/lipyd
cd lipyd/src
python
```

And then in Python:

```
import os
import importlib

for submodule in os.listdir('lipyd'):
  module_name, ext = os.splitext(submodule)
  if ext != '.py': continue
  print(f'Importing module `{module_name}`.')
  importlib.import_module(module_name)
```

> pycurl package can be installed, but hard to find a proper version.

I don't understand: `pycurl` is a pretty standard package, and its proper version is the latest stable release.

**Comment by NchuYJ** [comment]
Hi, my python encoding was utf8 but didn't set cmd.exe utf8 as default. The issue was solved. For the pycurl, your link in the webpage for installation was a little confusing,  direct `pip install pycurl` can perfectly work out?  

Thanks a lot
